// bun harness trace <base> <document> [operation] [--lib=<dir|ref>]
// What Node's V8 does differently with two builds on one of the bench's documents ("lines mixed", "worst controls",
// "rich latin"), offline: each function's bytecode length, what TurboFan inlines into what and what it refuses, which
// tier compiles each function, and which it deoptimizes and why (harness/README.md, Bench). The bundles are the
// bench's with their names kept; they run under Chrome's user agent over a stand-in Canvas (8 px a character at 16 px,
// 4 a space), each operation a fixed number of times, with --predictable so that two runs of one build print the same.
// Node's V8 isn't Chrome's: a difference here is a lead to time in the bench, and none found doesn't clear Chrome, nor
// says anything of Firefox or Safari. The 460 bytes are V8's max_inlined_bytecode_size (src/flags/flag-definitions.h,
// 1605 in V8 15.3): a function a byte longer isn't inlined, whatever calls it.
import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { benchBundle, buildName, srcOf } from './lib.ts'
import { documents, ROWS } from './run.ts'

const DRIVER = `const fs = require('fs')
Object.defineProperty(globalThis, 'navigator', { value: { userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36' }, configurable: true })
globalThis.OffscreenCanvas = class {
  getContext() {
    const context = {
      font: '10px sans-serif', letterSpacing: '0px',
      measureText(text) {
        let width = 0
        for (const ch of text) width += /[\\p{M}\\p{Cf}]/u.test(ch) ? 0 : (ch === ' ' ? 4 : 8) + parseFloat(context.letterSpacing)
        return { width: width * parseFloat(/(\\d+(?:\\.\\d+)?)px/.exec(context.font)[1]) / 16 }
      },
    }
    return context
  }
}
require('vm').runInThisContext(fs.readFileSync(process.argv[2], 'utf8'), { filename: 'bundle.js' })
const lib = globalThis.__benchLibrary
const doc = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'))
let sink = 0
for (const spec of doc.ops) {
  const texts = spec.batches === undefined ? spec.texts : spec.batches.flat()
  const data = spec.handles === undefined ? texts : lib.prepare(spec.handles, texts, doc.font, doc.options)
  const widths = spec.widths.length > 0 ? spec.widths : [243.3, 301.7, 356.1, 418.9]
  let units = 0
  for (const text of texts) units += typeof text === 'string' ? text.length : text.reduce((n, item) => n + (item.text === undefined ? 0 : item.text.length), 0)
  sink += lib.run(spec.op, data, widths, Math.ceil((spec.handles === undefined ? 2e6 : 6e7) / units), doc.font, doc.options)
}
console.log('sink', sink)
`

// Why V8 won't consider a function for inlining, which its trace prints as a number: SharedFunctionInfo::Inlineability
// (src/objects/shared-function-info.h), the same in V8 12.9 and 15.3.
const REFUSALS = ['no script', 'needs binary coverage', 'a builtin', 'not user code', 'no bytecode', 'over the bytecode limit', 'may contain breakpoints', 'optimization disabled']
function name(text: string): string {
  const found = /<(?:SharedFunctionInfo|JSFunction) ?([^ >(]*)/.exec(text)?.[1]
  return found === undefined ? '?' : found === '' ? '(anonymous)' : found
}
// The lines of one V8 trace that say something of a function, as "what: detail", without their addresses.
function facts(flags: string[], files: string[]): Set<string> {
  const run = spawnSync('node', ['--predictable', ...flags, ...files], { encoding: 'utf8', maxBuffer: 1 << 30, timeout: 300_000 })
  if (run.status !== 0) throw new Error(`node ${flags.join(' ')}: ${run.error?.message ?? run.stderr.slice(-400)}`)
  const out = new Set<string>()
  const lines = run.stdout.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!
    if (line.startsWith('[generated bytecode for function:')) out.add(`bytecode length: ${name(line)} ${/\d+/.exec(lines[i + 1] ?? '')?.[0] ?? '?'}`)
    else if (line.startsWith('Inlining ') && line.includes(' into ')) out.add(`inlined: ${name(line.split(' into ')[0]!)} into ${name(line.split(' into ')[1]!)}`)
    else if (line.startsWith('Cannot consider') && line.includes('SharedFunctionInfo')) out.add(`not inlined: ${name(line)} ${(/\(reason: [^)]*\)|\([^)]*\)$/.exec(line)?.[0] ?? '').replace(/reason: (\d+)/, (text, n) => REFUSALS[Number(n)] ?? text)}`)
    else if (line.startsWith('[completed compiling')) out.add(`compiled: ${name(line)} by ${/target (\w+)/.exec(line)?.[1] ?? '?'}`)
    else if (line.startsWith('[bailout')) out.add(`deoptimized: ${name(line)} from ${/<Code (\w+)>/.exec(line)?.[1] ?? '?'}, ${/reason: [^)]*/.exec(line)?.[0] ?? ''}`)
  }
  return out
}

export async function trace(baseRef: string, lib: string, id: string, op: string | undefined): Promise<string> {
  const doc = documents(ROWS, 'trace', false).find(d => d.id === id)
  if (doc === undefined || doc.fresh !== undefined) throw new Error(`trace takes a document that times operations: "lines mixed", "resize cjk", "worst controls", "rich latin"`)
  const ops = doc.ops.filter(spec => op === undefined || spec.op === op)
  if (ops.length === 0) throw new Error(`${id} has no operation ${op}: ${doc.ops.map(spec => spec.op).join(', ')}`)
  const dir = resolve(import.meta.dir, '../../.artifacts/harness-bench/trace')
  mkdirSync(dir, { recursive: true })
  const files = { driver: join(dir, 'driver.cjs'), doc: join(dir, 'doc.json') }
  writeFileSync(files.driver, DRIVER)
  writeFileSync(files.doc, JSON.stringify({ ...doc, ops }))
  const found: Array<Set<string>> = []
  for (const [label, ref] of [['base', baseRef], ['candidate', lib]] as const) {
    const bundle = join(dir, `${label}.js`)
    writeFileSync(bundle, (await benchBundle(srcOf(ref), true)).code)
    const all = new Set<string>()
    for (const flags of [['--print-bytecode', '--print-bytecode-filter=*'], ['--trace-turbo-inlining'], ['--trace-opt', '--trace-deopt']]) for (const fact of facts(flags, [files.driver, bundle, files.doc])) all.add(fact)
    found.push(all)
  }
  const [base, candidate] = found as [Set<string>, Set<string>]
  const only = (a: Set<string>, b: Set<string>): string[] => [...a].filter(fact => !b.has(fact)).sort()
  const version = spawnSync('node', ['-p', '`Node ${process.versions.node}, V8 ${process.versions.v8}`'], { encoding: 'utf8' }).stdout.trim()
  return [
    `${id}${op === undefined ? '' : ` ${op}`} under ${version}; base: ${buildName(baseRef)}; candidate: ${buildName(lib)}`,
    'only in base:', ...only(base, candidate).map(fact => `  ${fact}`), 'only in the candidate:', ...only(candidate, base).map(fact => `  ${fact}`),
    `the same in both: ${[...base].filter(fact => candidate.has(fact)).length} facts. TurboFan inlines no function over 460 bytes of bytecode.`,
  ].join('\n')
}
